### PR TITLE
added http script for logging the attempts

### PR DESCRIPTION
**Pull request by dhirensr**
related to https://github.com/zdresearch/OWASP-Honeypot/issues/42

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
why you didn't use normal apache/nginx instead?

**Comment by dhirensr** [comment]
@Ali-Razmjoo : HTTPServer lib is shipped with python and for sniffing with apache/nginx we have to write custom script which is listening to port and extracting something.
I thought this would be easier for script and feasible too.

**Comment by Ali-Razmjoo** [comment]
please use normal webserver to avoid having signatures from python... it makes honeypot detectable

**Comment by Ali-Razmjoo** [comment]
please follow this ... https://github.com/zdresearch/OWASP-Honeypot/commit/42d08ce7cdb94cb5a92ddc0628aa8d117a57c48e

after configuration accesslog will be like: 

```
root@0ec2ad46eba1:/var/log# cat apache2/access.log 
{ "ip": "127.0.0.1", "time": "[04/Aug/2019:17:40:29 +0000]", "request": "HEAD / HTTP/1.1", "status": 500, "user_agent": "curl/7.47.0", "authorization": "-" }
{ "ip": "127.0.0.1", "time": "[04/Aug/2019:17:40:34 +0000]", "request": "GET / HTTP/1.1", "status": 500, "user_agent": "curl/7.47.0", "authorization": "-" }
{ "ip": "127.0.0.1", "time": "[04/Aug/2019:17:42:01 +0000]", "request": "GET / HTTP/1.1", "status": 401, "user_agent": "curl/7.47.0", "authorization": "-" }
{ "ip": "127.0.0.1", "time": "[04/Aug/2019:17:42:06 +0000]", "request": "GET / HTTP/1.1", "status": 401, "user_agent": "curl/7.47.0", "authorization": "Basic dGVzdDphbGk=" }
{ "ip": "172.18.0.1", "time": "[04/Aug/2019:17:42:22 +0000]", "request": "GET / HTTP/1.1", "status": 401, "user_agent": "curl/7.58.0", "authorization": "Basic dGVzdDphZG1pbg==" }
```

and then do the logging creds and moving/emptying the file. (if you move/remove the file i think you need to create a new one  (not sure if apache will create a new one))

**Comment by Ali-Razmjoo** [comment]
you may modify the log in apache2.conf in here and add whatever its needed.

```
LogFormat "{ \"ip\": \"%h\", \"time\": \"%t\", \"request\": \"%r\", \"status\": %>s, \"user_agent\": \"%{User-Agent}i\", \"authorization\": \"%{Authorization}i\" }" combined
CustomLog /var/log/apache2/access.log combined
```

**Comment by dhirensr** [comment]
@Ali-Razmjoo : thanks a lot! will send a PR completing this week

**Comment by Ali-Razmjoo** [comment]
fixed the error, please proceed the developing.

**Pull request merged**
