### PR TITLE
Add a development environment setup script

### PR DESCRIPTION
**Pull request by ChakshuGupta**
Installs mongodb
Installs python requirements

### CODE REVIEW

**Comment by dhirensr** [comment]
@ChakshuGupta : Thank you for your interest and PR. 
could you please explain how would the script be useful for the repository?

**Comment by ChakshuGupta** [comment]
Hi,

It would be useful to have the installation of all the required packages in one script.  It helps with anyone wanting to contribute as it eases up the process of setting up the required development environment.

**Comment by dhirensr** [comment]
@ChakshuGupta : I agree that this would be useful script to install all the dependencies. However it's OS specific and wouldn't work on all Operation Systems.
Hence I think we would not integrate this for now. 
@Ali-Razmjoo : what do you think?

**Comment by ChakshuGupta** [comment]
Okay! Thank you! I'll start working on other tasks!

**Comment by Ali-Razmjoo** [comment]
Hi, thanks for the PR,

actually if you can convert this script to a dockerfile, it will solve this card ... https://github.com/zdresearch/OWASP-Honeypot/projects/1#card-22046785

Bests.

**Comment by ChakshuGupta** [comment]
Hi,

Great! I'll get on it.

**Comment by dhirensr** [comment]
@ChakshuGupta : should you need any help just send a PR and I can help. :smile:

**Comment by ChakshuGupta** [comment]
Thanks. I have sent it in a PR.

**Comment by Ali-Razmjoo** [comment]
is this PR migrated to #75?

**Comment by dhirensr** [comment]
@Ali-Razmjoo : yes

**Pull request closed without merging**
