### PR TITLE
making changes with travis bot for testing env

### PR DESCRIPTION
**Pull request by dhirensr**
@Ali-Razmjoo : adding pytest and codecoverage package and made requirements-dev.txt for testing environment so that user won't have to run the tests.
problem is that once we update requirements.txt ,then we need to keep in mind to update requirements-dev.txt also or maybe we can remove requirements-dev and add pytest and codecov to requirements.txt ! please give a review for this

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
what's the purpose? 🤔

**Comment by dhirensr** [comment]
purpose is we need pytest and codecov for testing.
should we create new requirments-dev.txt or just add the package in requirements.txt?

**Comment by Ali-Razmjoo** [comment]
nah you are right I will merge it once if fixed CI...

**Comment by Ali-Razmjoo** [comment]
thanks for this, I merged #57 instead.

**Pull request closed without merging**
