### PR TITLE
Enhanced verbose output 

### PR DESCRIPTION
**Pull request by AlphaRoy14**
Displays packet information in real time on the terminal. Related to issue #68

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
thanks for the PR, we are missing some events coming from module processor, and it's better to add the verbose mode in database.py https://github.com/zdresearch/OWASP-Honeypot/blob/master/database/connector.py

* insert_selected_modules_network_event
* insert_other_network_event
* insert_events_in_bulk
* insert_bulk_events_from_thread
* insert_honeypot_events_credential_from_module_processor
* insert_honeypot_events_data_from_module_processor

and i think it would be better to be printed as info() instead of warn. (or maybe we can create verbose_info()).

**Comment by AlphaRoy14** [comment]
Thanks for the review, I'll make the changes.

**Comment by AlphaRoy14** [comment]
@Ali-Razmjoo Hi! I have refactored the verbose code to the database module. As on now it prints IP and Port info for non honeypot events. IP, Port and module name for honeypot events. If you want I can add certain module processor features like username, password, data etc if you like. However, the screen gets covered with too many information if all the module processor features are incorporated. Please let me know changes to be made.

**Comment by Ali-Razmjoo** [comment]
@AlphaRoy14 thanks for the PR, I've changed a little bit because verbose_info shall be used for all type of verbose information not limited to honeypot event function. let @dhirensr have a test and review and i will merge it.

**Pull request merged**
