### PR TITLE
 Top network ip by country 

### PR DESCRIPTION
**Pull request by dhirensr**
what : changed the sort conditions as
network->country->top_ips

@Ali-Razmjoo  : please review and give feedback regarding changes!

### CODE REVIEW

**Comment by dhirensr** [comment]
@Ali-Razmjoo : i sent the other pr also and would be sending more PR and would create tickets also for them! when would you reply about the review of PR? 
I just can see that  [Ali-Razmjoo](/Ali-Razmjoo) self-requested a review [2 days ago](#event-2144922204),
don't know what that means because i am new to open source contribution.

**Comment by Ali-Razmjoo** [comment]
Hi, I will review your PRs in the weekend, thanks for your contribution.

**Comment by Ali-Razmjoo** [comment]
it's a bit confusing "top network ip by country" and I was expecting to get the "country" as input and get the top repeated ips, but what you meant was top individual repeated ips in countries, which is a bit weird.

my suggestion is to get the country from users input, and then search for the top repeated ips...

**Comment by dhirensr** [comment]
@Ali-Razmjoo : will work on your suggestion and send a PR soon! thanks for replying

**Comment by dhirensr** [comment]
@Ali-Razmjoo  : modified the route and its working fine ! it would be great if you review and give feedback !
the usage of the routes is   http://127.0.0.1:5000/api/events/top_network_ips_by_country?country=US

if no problems then i would add the top honeypot/network ip by country by date and also top hoeypot/network ports by country.

**Comment by Ali-Razmjoo** [comment]
why you used `bytes(country,'utf-8')`?

**Comment by dhirensr** [comment]
@Ali-Razmjoo : in honeypot_events and network_events ,i.e. all records of databases retrieved have country as type bytes,so to compare them I needed to convert the string to bytes.
Other option would be to convert the country attribute of records retrieved as string,and that I thought wouldn't be a good option.
The records fetched from a database looks like : 
```shell 
{'_id': ObjectId('5c6ab8c08f5e3d0889ebbff9'), 'ip': '129.69.182.80', 'port': 80, 'module_name': 'http/basic_auth_strong_password', 'date': '2019-02-18 14:53:04', 'country': b'DE'}
```
the type for country is bytes

**Comment by Ali-Razmjoo** [comment]
this is what I get from the function...

```
In [17]: [ 
    ...:                 i for i in 
    ...:                 connector.honeypot_events.aggregate( 
    ...:                     [ 
    ...:                         { 
    ...:                             "$match": 
    ...:                                 { 
    ...:                                     "country": country, 
    ...:                                 } 
    ...:                         }, 
    ...:                         { 
    ...:                             "$group": 
    ...:                                 { 
    ...:                                     "_id": 
    ...:                                         { 
    ...:                                             "ip": "$ip", 
    ...:                                             "country": "$country", 
    ...:                                         }, 
    ...:                                     "count": 
    ...:                                         { 
    ...:                                             "$sum": 1 
    ...:                                         } 
    ...:                                 } 
    ...:                         }, 
    ...:                         { 
    ...:                             "$sort": 
    ...:                                 SON( 
    ...:                                     [ 
    ...:                                         ("count", -1), 
    ...:                                         ("_id", -1) 
    ...:                                     ] 
    ...:                                 ) 
    ...:                         }, 
    ...:                         { 
    ...:                             "$skip": fix_skip(get_value_from_request("skip")) 
    ...:                         }, 
    ...:                         { 
    ...:                             "$limit": fix_limit(get_value_from_request("limit")) 
    ...:                         } 
    ...:                     ] 
    ...:                 ) 
    ...:             ]                                                                                                                                                                                                                        
Out[17]: 
[{'_id': {'ip': '104.131.146.17', 'country': 'US'}, 'count': 33},
 {'_id': {'ip': '45.76.16.165', 'country': 'US'}, 'count': 18},
 {'_id': {'ip': '185.53.88.24', 'country': 'US'}, 'count': 18},
 {'_id': {'ip': '155.138.207.97', 'country': 'US'}, 'count': 18},
 {'_id': {'ip': '184.105.139.67', 'country': 'US'}, 'count': 9},
 {'_id': {'ip': '198.255.56.138', 'country': 'US'}, 'count': 6},
 {'_id': {'ip': '138.197.206.217', 'country': 'US'}, 'count': 6},
 {'_id': {'ip': '74.82.47.57', 'country': 'US'}, 'count': 3},
 {'_id': {'ip': '184.105.139.107', 'country': 'US'}, 'count': 3}]

In [18]: json.dumps(_)                                                                                                                                                                                                                        
Out[18]: '[{"_id": {"ip": "104.131.146.17", "country": "US"}, "count": 33}, {"_id": {"ip": "45.76.16.165", "country": "US"}, "count": 18}, {"_id": {"ip": "185.53.88.24", "country": "US"}, "count": 18}, {"_id": {"ip": "155.138.207.97", "country": "US"}, "count": 18}, {"_id": {"ip": "184.105.139.67", "country": "US"}, "count": 9}, {"_id": {"ip": "198.255.56.138", "country": "US"}, "count": 6}, {"_id": {"ip": "138.197.206.217", "country": "US"}, "count": 6}, {"_id": {"ip": "74.82.47.57", "country": "US"}, "count": 3}, {"_id": {"ip": "184.105.139.107", "country": "US"}, "count": 3}]'
```

`jsonify` should fix it for you...

**Comment by dhirensr** [comment]
@Ali-Razmjoo : 
this is what I am getting for an hardcoded string in country,
```shell
[
                i for i in
                connector.honeypot_events.aggregate(
                    [
                        {
                            "$match":

                            {
                                "country" : bytes('DE','utf-8'),
                            }
                        },
                        {
                            "$group":
                            {
                                "_id":
                                {
                                    "ip": "$ip",
                                    "country": "$country",
                                },
                                "count":
                                {
                                    "$sum": 1
                                }
                            }
                        },
                        {
                            "$sort":
                            SON(
                                [   ("count", -1),
                                    ("_id", -1)
                                ]
                            )
                        },
                        {
                            "$skip": fix_skip(get_value_from_request("skip"))
                        },
                        {
                            "$limit": fix_limit(get_value_from_request("limit"))
                        }
                    ]
                )
            ]

Output: 
[{"_id":{"country":"DE","ip":"129.69.182.80"},"count":30}]
```
and when Input is without bytes,
``` shell
[
                i for i in
                connector.honeypot_events.aggregate(
                    [
                        {
                            "$match":

                            {
                                "country" : 'DE',
                            }
                        },
                        {
                            "$group":
                            {
                                "_id":
                                {
                                    "ip": "$ip",
                                    "country": "$country",
                                },
                                "count":
                                {
                                    "$sum": 1
                                }
                            }
                        },
                        {
                            "$sort":
                            SON(
                                [   ("count", -1),
                                    ("_id", -1)
                                ]
                            )
                        },
                        {
                            "$skip": fix_skip(get_value_from_request("skip"))
                        },
                        {
                            "$limit": fix_limit(get_value_from_request("limit"))
                        }
                    ]
                )
            ]

OUTPUT : 
[]
```
and then jsonify is applied to them ,so for querying in mongo I needed to convert it to bytes

**Comment by Ali-Razmjoo** [comment]
oh that means we have another bug then in here https://github.com/zdresearch/OWASP-Honeypot/blob/master/api/server.py#L47-L71

let me check if I can fix it...

**Comment by Ali-Razmjoo** [comment]
my bad, bug was in ip2location, can you insert new data and check if it save as str or byte?

**Comment by dhirensr** [comment]
@Ali-Razmjoo : it works fine now! and I changed the routes and committed it! 
the routes are fine right? then i can continue with date and ports also?

**Comment by Ali-Razmjoo** [comment]
it gets a lot of conflicts, could you update the branch or send all changes in new PR?

**Comment by dhirensr** [comment]
Done https://github.com/zdresearch/OWASP-Honeypot/pull/21 @Ali-Razmjoo

**Pull request closed without merging**
