### PR TITLE
replaced socket.gethostname()

### PR DESCRIPTION
**Pull request by Simran-bhardwaj**
worked on issue #40 

fixes
Not printing logo on macOS in
OWASP-Honeypot/config.py

Proposed:
Replace socket.gethostname() with ""

Testing:

Screenshot 2020-02-23 at 12 01 24 PM

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Hi,

Thanks for the PR and your contribution, can you describe the issue more? i am using mac os but couldn’t understand what issue you solved 


Thank you.

**Comment by Simran-bhardwaj** [comment]
hi
I am also using mac OS.
The issue which was opened by you https://github.com/zdresearch/OWASP-Honeypot/issues/40, in which ohp.py file doesn't printing anything, I just tried to solve that one, after replacing socket.gethostname() by "" in config.py file, I found that it started to print the logo.

**Comment by Ali-Razmjoo** [comment]
The issue in #40, fixed by #44 PR, do you still have the issue?

**Comment by Simran-bhardwaj** [comment]
But why this issue is still open?

**Comment by Ali-Razmjoo** [comment]
I think I forget to close the issue, and thank you for your consideration.

**Pull request closed without merging**
