### PR TITLE
Fix bug in docker-compose-host file

### PR DESCRIPTION
**Pull request by ChakshuGupta**
The PR #126 had a couple of bugs in the docker-compose-host file. 

It needs the `network_mode: host` mode to be able to connect to mongodb running on the host computer.
And there was a typo in the `volumes`.

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
I've fixed the typo in volums but not sure about the `network_mode: host` I've tested it on CI and my PC, it's working, you need to set the gateway IP as your mongodb or some valid address.

**Comment by Ali-Razmjoo** [comment]
I just had it tested...

```
batman@Batmans-MacBook-Pro:~/D/G/OWASP-Honeypot:development$ cat docker-compose-host-ci.yml
version: '3'

services:
  ohp:
    build:
      context: .
      dockerfile: "Dockerfile.api"
    command: bash -c "sleep 5 && python3 ohp.py --start-api-server"
    environment:
      - FLASK_ENV=development
      - CI_ENV=true
    ports:
      - 5000:5000
    volumes:
      - .:/OWASP-Honeypot
#    network_mode: host⏎                                                                                                                                                                                        batman@Batmans-MacBook-Pro:~/D/G/OWASP-Honeypot:development$ docker-compose  -f docker-compose-host-ci.yml up
Starting owasp-honeypot_ohp_1 ... done
Attaching to owasp-honeypot_ohp_1
ohp_1  |
ohp_1  |       ______          __      _____ _____
ohp_1  |      / __ \ \        / /\    / ____|  __ \
ohp_1  |     | |  | \ \  /\  / /  \  | (___ | |__) |
ohp_1  |     | |  | |\ \/  \/ / /\ \  \___ \|  ___/
ohp_1  |     | |__| | \  /\  / ____ \ ____) | |
ohp_1  |      \____/   \/  \/_/    \_\_____/|_|
ohp_1  |                       _    _                        _____      _
ohp_1  |                      | |  | |                      |  __ \    | |
ohp_1  |                      | |__| | ___  _ __   ___ _   _| |__) |__ | |_
ohp_1  |                      |  __  |/ _ \| "_ \ / _ \ | | |  ___/ _ \| __|
ohp_1  |                      | |  | | (_) | | | |  __/ |_| | |  | (_) | |_
ohp_1  |                      |_|  |_|\___/|_| |_|\___|\__, |_|   \___/ \__|
ohp_1  |                                                __/ |
ohp_1  |                                               |___/
ohp_1  |
ohp_1  |  * API access key: NOT REQUIRED!
ohp_1  |  * Serving Flask app "api.server" (lazy loading)
ohp_1  |  * Environment: development
ohp_1  |  * Debug mode: off
ohp_1  |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

```

```
batman@Batmans-MacBook-Pro:~/D/G/OWASP-Honeypot:development$ cat docker-compose-host-ci.yml
version: '3'

services:
  ohp:
    build:
      context: .
      dockerfile: "Dockerfile.api"
    command: bash -c "sleep 5 && python3 ohp.py --start-api-server"
    environment:
      - FLASK_ENV=development
      - CI_ENV=true
    ports:
      - 5000:5000
    volumes:
      - .:/OWASP-Honeypot
    network_mode: host⏎                                                                                                                                                                                         batman@Batmans-MacBook-Pro:~/D/G/OWASP-Honeypot:development$ docker-compose  -f docker-compose-host-ci.yml up
Recreating owasp-honeypot_ohp_1 ... done
Attaching to owasp-honeypot_ohp_1
ohp_1  |
ohp_1  |       ______          __      _____ _____
ohp_1  |      / __ \ \        / /\    / ____|  __ \
ohp_1  |     | |  | \ \  /\  / /  \  | (___ | |__) |
ohp_1  |     | |  | |\ \/  \/ / /\ \  \___ \|  ___/
ohp_1  |     | |__| | \  /\  / ____ \ ____) | |
ohp_1  |      \____/   \/  \/_/    \_\_____/|_|
ohp_1  |                       _    _                        _____      _
ohp_1  |                      | |  | |                      |  __ \    | |
ohp_1  |                      | |__| | ___  _ __   ___ _   _| |__) |__ | |_
ohp_1  |                      |  __  |/ _ \| "_ \ / _ \ | | |  ___/ _ \| __|
ohp_1  |                      | |  | | (_) | | | |  __/ |_| | |  | (_) | |_
ohp_1  |                      |_|  |_|\___/|_| |_|\___|\__, |_|   \___/ \__|
ohp_1  |                                                __/ |
ohp_1  |                                               |___/
ohp_1  |
ohp_1  | [X] [2020-08-10 11:21:59] cannot connect to mongodb
ohp_1  | owasp-honeypot_ohp_1 exited with code 1

```

@dhirensr can you also have a test?

**Comment by ChakshuGupta** [comment]
@Ali-Razmjoo It is not needed in the docker-compose-host-ci.yml as there were are connecting it to the gateway IP address that is why CI is passing. 
But in docker-compose-host.yml it is needed as we are trying to connect to `127.0.0.1` IP address for mongodb and it needs to be on the same network as the host for that.

`docker-compose -f docker-compose-host.yml up` will give an error as that connects to `mongodb://127.0.0.1:27017/` and that gives an error.

**Comment by Ali-Razmjoo** [comment]
in that host.yml shall work on ci too. I will merge it if it pass the tests.

**Comment by dhirensr** [comment]
@Ali-Razmjoo : it's failing locally without ``` network_mode: host``` for me

**Pull request merged**
