### PR TITLE
Log explorer

### LINKED ISSUE #67: log explorer
It would be nice to have a log explorer in webui with search and export features.

### PR DESCRIPTION
**Pull request by ChakshuGupta**
Fixes #67

1. Log explorer to view and export the event data collected in the database.
2. Minor UI updates

The screenshots for the explorer:

Screenshot from 2020-07-04 19-08-39
Screenshot from 2020-07-04 19-08-30

### CODE REVIEW

**Comment by dhirensr** [comment]
@ChakshuGupta : Looks awesome!
There are 2 problems with the UI I noticed while testing locally:
1. when I am inside the log explorer and I select Honeypot events I don't the table populated with src IP ,Dest,etc but the api (http://127.0.0.1:5000/api/events/get-events-data?event_type=honeypot-event&start_date=2007-07-08&end_date=2020-07-01&limit=1000&_=1594406209471) which that table is using is returning the information. The information is not being consumed by the frontend.

2. when I download the file excel/csv the name has double file endings. I guess maybe few operating systems won't be able to open this so we could fix this minor thing.
for eg : the file name looks like Honeypot-data-excel-1594406554638.xlsx.xlsx instead should be Honeypot-data-excel-1594406554638.xlsx

**Comment by ChakshuGupta** [comment]
@dhirensr  Thanks! 
I am not able to recreate the 1st issue, it is populating the data for me. Could you export data returned by the API call and send it to me?

I fixed the file naming issue.

**Comment by dhirensr** [comment]
@ChakshuGupta : this is output data I'm getting [output.txt](https://github.com/zdresearch/OWASP-Honeypot/files/4909375/output.txt)

**Comment by Ali-Razmjoo** [comment]
this seems very good now, I need to do more tests before merging, thanks you @ChakshuGupta and @dhirensr 👍

**Comment by ChakshuGupta** [comment]
@Ali-Razmjoo It won't be a big change as only one more database would need to be added to the list.

**Pull request merged**
